import Image from "next/image";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const machineImages = {
  liquid: "/uploads/products/1789454102897-8e2735e48922.jpg",
  viscous: "/uploads/products/1789453520828-9daa24375963.jpg",
};
const industries = ["PHARMACEUTICALS", "COSMETICS", "HEALTHCARE", "CHEMICALS", "HERBAL", "FOOD", "ADHESIVES", "PERSONAL CARE"];
const qualityParameters = ["EFFICIENCY", "LONGER LIFE", "DURABILITY", "ROBUSTNESS", "LOW POWER CONSUMPTION"];
const applications = ["Ointments", "Creams", "Balms", "Pastes", "Jams", "Sauces", "Gums", "Glues", "Chyawanprash", "Mehndi"];

function BlueprintMark() {
  return <svg viewBox="0 0 440 260" className="pointer-events-none absolute right-0 top-0 h-full w-1/2 text-[#1F3A5F]/[.07]" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="1"><circle cx="285" cy="118" r="95" /><circle cx="285" cy="118" r="61" /><path d="M0 118h440M285 0v260M85 40l300 155M109 225l291-166M190 23l190 190" /><rect x="235" y="68" width="101" height="100" /></g></svg>;
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return <p className="flex items-center gap-3 font-mono text-[10px] font-semibold uppercase tracking-[.18em] text-[#1F3A5F]"><span className="h-px w-8 bg-[#1F3A5F]" />{children}</p>;
}

export const metadata = { title: "About Kashyap Engineering | Packaging Machinery", description: "Kashyap Engineering manufactures filling and packaging machinery from Vadodara, Gujarat, India." };

export default function AboutPage() {
  return <><Navbar /><main className="overflow-hidden bg-[#F7F5F1] text-[#1C2024]">
    <section className="relative border-b border-[#D8D3C8] bg-white"><BlueprintMark /><div className="mx-auto grid min-h-[680px] max-w-7xl items-center gap-12 px-6 py-20 lg:grid-cols-12 lg:gap-8 lg:py-28"><div className="relative z-10 lg:col-span-6"><SectionLabel>About Kashyap Engineering</SectionLabel><h1 className="mt-7 max-w-2xl font-display text-5xl font-bold leading-[.94] tracking-[-.06em] md:text-7xl">Engineering packaging solutions built around precision.</h1><p className="mt-8 max-w-xl text-base leading-7 text-[#5B6472]">Kashyap Engineering is a leading manufacturer and solution provider in tube-filling, packaging and liquid-filling machinery.</p><p className="mt-7 font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#6B7480]">EST. 2009 <span className="mx-2 text-[#1F3A5F]">·</span> VADODARA, INDIA <span className="mx-2 text-[#1F3A5F]">·</span> ISO 9001:2015</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/products" className="bg-[#1268D4] px-6 py-3 text-xs font-bold uppercase tracking-[.1em] text-white transition hover:bg-[#1F3A5F]">Explore our machines <span className="ml-3">→</span></Link><Link href="/contact" className="border border-[#D8D3C8] bg-white px-6 py-3 text-xs font-bold uppercase tracking-[.1em] text-[#1F3A5F] transition hover:border-[#1268D4]">Talk to our engineers</Link></div></div><div className="relative lg:col-span-6 lg:pl-8"><div className="relative aspect-[4/3] overflow-hidden border border-[#D8D3C8] bg-white"><Image src={machineImages.liquid} alt="Liquid filling machine" fill priority className="object-contain p-5 mix-blend-multiply" /></div><div className="absolute -bottom-5 -left-5 border border-[#D8D3C8] bg-[#F7F5F1] px-4 py-3 font-mono text-[9px] uppercase tracking-[.14em] text-[#6B7480]">ENGINEERING / 001</div></div></div></section>

    <section className="relative mx-auto max-w-7xl px-6 py-24 lg:py-32"><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-7"><SectionLabel>Company introduction</SectionLabel><h2 className="mt-6 max-w-2xl font-display text-4xl font-bold leading-[.98] tracking-[-.05em] md:text-6xl">Engineering packaging solutions since 2009.</h2></div><div className="lg:col-span-4 lg:col-start-9"><p className="text-base leading-8 text-[#5B6472]">Kashyap Engineering is a Vadodara-based manufacturer of liquid filling, oil filling, bottle filling and tube filling machines. We design practical systems around production requirements, dependable performance and the needs of the production line.</p></div></div><div className="mt-20 grid border-y border-[#D8D3C8] md:grid-cols-3"><div className="border-b border-[#D8D3C8] py-7 md:border-b-0 md:border-r"><p className="font-display text-5xl font-bold tracking-[-.06em] text-[#1F3A5F]">2009</p><p className="mt-2 font-mono text-[10px] uppercase tracking-[.14em] text-[#6B7480]">Established</p></div><div className="border-b border-[#D8D3C8] py-7 md:border-b-0 md:border-r md:pl-8"><p className="font-display text-5xl font-bold tracking-[-.06em] text-[#1F3A5F]">ISO</p><p className="mt-2 font-mono text-[10px] uppercase tracking-[.14em] text-[#6B7480]">9001:2015 certified</p></div><div className="py-7 md:pl-8"><p className="font-display text-5xl font-bold tracking-[-.06em] text-[#1F3A5F]">Vadodara</p><p className="mt-2 font-mono text-[10px] uppercase tracking-[.14em] text-[#6B7480]">Manufacturing base</p></div></div></section>

    <section className="border-y border-[#D8D3C8] bg-white px-6 py-24 lg:py-32"><div className="mx-auto max-w-7xl"><SectionLabel>What we manufacture</SectionLabel><div className="mt-6 flex flex-col justify-between gap-6 md:flex-row md:items-end"><h2 className="max-w-2xl font-display text-4xl font-bold leading-none tracking-[-.05em] md:text-6xl">Built around your production requirements.</h2><Link href="/products" className="shrink-0 font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#1268D4]">View all machines →</Link></div><div className="mt-14 grid gap-px bg-[#D8D3C8] md:grid-cols-3"><Link href="/products" className="group bg-white p-4"><div className="relative aspect-[4/3] overflow-hidden bg-[#F7F5F1]"><Image src={machineImages.liquid} alt="Tube filling machines" fill className="object-contain mix-blend-multiply transition duration-500 group-hover:scale-105" /></div><p className="mt-5 font-mono text-[10px] uppercase tracking-[.14em] text-[#1F3A5F]">01 / Category</p><h3 className="mt-2 text-xl font-semibold">Tube Filling Machines</h3><p className="mt-4 text-sm text-[#6B7480]">Explore <span className="text-[#1268D4]">→</span></p></Link><Link href="/products" className="group bg-white p-4"><div className="relative aspect-[4/3] overflow-hidden bg-[#F7F5F1]"><Image src={machineImages.viscous} alt="Liquid filling machines" fill className="object-contain mix-blend-multiply transition duration-500 group-hover:scale-105" /></div><p className="mt-5 font-mono text-[10px] uppercase tracking-[.14em] text-[#1F3A5F]">02 / Category</p><h3 className="mt-2 text-xl font-semibold">Liquid Filling Machines</h3><p className="mt-4 text-sm text-[#6B7480]">Explore <span className="text-[#1268D4]">→</span></p></Link><Link href="/products" className="group bg-white p-4"><div className="relative flex aspect-[4/3] items-center justify-center overflow-hidden bg-[#E8EEF4] text-[#1F3A5F]"><div className="h-32 w-52 border border-current opacity-70"><div className="m-5 h-20 border border-current" /></div></div><p className="mt-5 font-mono text-[10px] uppercase tracking-[.14em] text-[#1F3A5F]">03 / Category</p><h3 className="mt-2 text-xl font-semibold">Packaging Machinery</h3><p className="mt-4 text-sm text-[#6B7480]">Explore <span className="text-[#1268D4]">→</span></p></Link></div></div></section>

    <section className="relative mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-12 lg:items-center lg:py-32"><div className="lg:col-span-5"><SectionLabel>Featured machine</SectionLabel><h2 className="mt-6 font-display text-4xl font-bold leading-[.98] tracking-[-.05em] md:text-6xl">Engineering the next generation of filling.</h2><p className="mt-7 text-base leading-8 text-[#5B6472]">The Automatic PLC Based Viscous Liquid Filling Machine is designed for filling water and viscous liquids such as sauces, oils, liquid detergent, hand wash, shampoo and hand sanitiser.</p><ul className="mt-8 grid gap-3 border-t border-[#D8D3C8] pt-5 text-sm text-[#1C2024] sm:grid-cols-2"><li>PLC operated</li><li>User-friendly operation</li><li>No change parts required</li><li>Available in India, Dubai and South Africa</li></ul></div><div className="relative lg:col-span-7"><div className="relative aspect-[4/3] overflow-hidden border border-[#D8D3C8] bg-white"><Image src={machineImages.viscous} alt="Automatic PLC based viscous liquid filling machine" fill className="object-contain p-8 mix-blend-multiply" /></div><span className="absolute -bottom-4 right-4 bg-[#1F3A5F] px-4 py-3 font-mono text-[9px] uppercase tracking-[.14em] text-white">PLC / AUTOMATION / 002</span></div></section>

    <section className="border-y border-[#D8D3C8] bg-[#1F3A5F] px-6 py-24 text-white lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-12"><div className="lg:col-span-5"><p className="flex items-center gap-3 font-mono text-[10px] font-semibold uppercase tracking-[.18em] text-[#D7E0E8]"><span className="h-px w-8 bg-[#D7E0E8]" />Industries & applications</p><h2 className="mt-6 font-display text-4xl font-bold leading-none tracking-[-.05em] md:text-6xl">One engineering capability. Countless applications.</h2></div><div className="lg:col-span-6 lg:col-start-7"><div className="grid grid-cols-2 border-l border-white/25">{industries.map((industry) => <div key={industry} className="border-b border-r border-t border-white/25 px-4 py-4 font-mono text-[10px] tracking-[.12em] text-[#D7E0E8]">{industry}</div>)}</div><p className="mt-8 max-w-xl text-sm leading-7 text-[#C4D0DB]">Filling materials include ointments, creams, balms, pastes, jams, sauces, gums, glues, Chyawanprash and mehndi.</p><div className="mt-6 flex flex-wrap gap-2">{applications.map((application) => <span key={application} className="border border-white/20 px-3 py-2 text-xs text-[#E8EEF4]">{application}</span>)}</div></div></div></section>

    <section className="mx-auto max-w-7xl px-6 py-24 lg:py-32"><div className="grid gap-12 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-6"><SectionLabel>Infrastructure</SectionLabel><h2 className="mt-6 max-w-xl font-display text-4xl font-bold leading-none tracking-[-.05em] md:text-6xl">Built in Vadodara. Engineered for demanding production.</h2><p className="mt-7 max-w-lg text-base leading-8 text-[#5B6472]">Kashyap Engineering has sophisticated production facilities and technically advanced automatic machinery, with flexible production capacity for domestic and international requirements.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:col-span-6"><div className="relative aspect-[3/4] border border-[#D8D3C8] bg-white sm:translate-y-10"><Image src={machineImages.liquid} alt="Kashyap Engineering filling equipment" fill className="object-contain p-4 mix-blend-multiply" /></div><div className="relative aspect-[3/4] border border-[#D8D3C8] bg-white"><Image src={machineImages.viscous} alt="Kashyap Engineering liquid filling equipment" fill className="object-contain p-4 mix-blend-multiply" /></div></div></div></section>

    <section className="relative border-y border-[#D8D3C8] bg-white px-6 py-24 lg:py-32"><BlueprintMark /><div className="relative mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-5"><SectionLabel>Quality assurance</SectionLabel><h2 className="mt-6 font-display text-4xl font-bold leading-none tracking-[-.05em] md:text-6xl">Quality is engineered into every machine.</h2><p className="mt-7 max-w-md text-base leading-8 text-[#5B6472]">We focus on quality raw materials, reliable vendors and stringent quality-control measures to deliver dependable equipment.</p></div><div className="lg:col-span-6 lg:col-start-7">{qualityParameters.map((parameter, index) => <div key={parameter} className="flex items-center gap-5 border-b border-[#D8D3C8] py-5"><span className="font-mono text-xs text-[#1268D4]">0{index + 1}</span><span className="font-display text-2xl font-semibold tracking-[-.03em] md:text-4xl">{parameter}</span></div>)}</div></div></div></section>

    <section className="mx-auto max-w-7xl px-6 py-24 lg:py-32"><div className="grid gap-14 lg:grid-cols-12"><div className="lg:col-span-5"><SectionLabel>Customer satisfaction</SectionLabel><h2 className="mt-6 font-display text-4xl font-bold leading-none tracking-[-.05em] md:text-6xl">Designed around the customer.</h2><p className="mt-7 text-base leading-8 text-[#5B6472]">We combine innovation, technological advancement and customer-specific requirements to achieve customer satisfaction.</p></div><div className="lg:col-span-6 lg:col-start-7"><div className="border-t border-[#D8D3C8]">{["CUSTOMER REQUIREMENT", "ENGINEERING", "MANUFACTURING", "TESTING", "DELIVERY"].map((step, index) => <div key={step} className="flex items-center gap-5 border-b border-[#D8D3C8] py-5"><span className="font-mono text-xs text-[#1268D4]">0{index + 1}</span><span className="text-sm font-semibold tracking-[.12em]">{step}</span>{index < 4 && <span className="ml-auto text-[#1F3A5F]">↓</span>}</div>)}</div></div></div></section>

    <section className="border-t border-[#D8D3C8] bg-[#E8EEF4] px-6 py-24 lg:py-32"><div className="mx-auto max-w-7xl"><SectionLabel>Start a conversation</SectionLabel><div className="mt-6 grid gap-10 lg:grid-cols-12 lg:items-end"><h2 className="font-display text-5xl font-bold leading-[.92] tracking-[-.06em] md:text-7xl lg:col-span-7">Have a packaging requirement?</h2><div className="lg:col-span-4 lg:col-start-9"><p className="text-base leading-7 text-[#5B6472]">Let&apos;s discuss the right engineering solution for your application.</p><Link href="/contact" className="mt-7 inline-flex bg-[#1268D4] px-6 py-3 text-xs font-bold uppercase tracking-[.1em] text-white transition hover:bg-[#1F3A5F]">Request a quote <span className="ml-3">→</span></Link><a href="mailto:nitinp9800@gmail.com" className="mt-7 block font-mono text-xs tracking-[.08em] text-[#1F3A5F] hover:text-[#1268D4]">nitinp9800@gmail.com</a></div></div></div></section>
  </main><Footer /></>;
}